# Generated by Django 6.0.2 on 2026-04-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_auditlog_fileanalytics_documentversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
    ]
