# Generated by Django 6.0.2 on 2026-04-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tenant_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='raw_file',
            field=models.FileField(blank=True, null=True, upload_to='temp_uploads/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Encryption'), ('ready', 'Ready'), ('failed', 'Encryption Failed')], default='ready', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='encrypted_file',
            field=models.FileField(blank=True, upload_to='encrypted_docs/%Y/%m/'),
        ),
    ]
