"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import environ
import os

# Initialize environ
env = environ.Env(
    DEBUG=(bool, False)
)

# Set the project base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file (ignored in production — env vars set directly on server)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# ─────────────────────────────────────────────
# Core Security Settings
# ─────────────────────────────────────────────
SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])


# ─────────────────────────────────────────────
# Application Definition
# ─────────────────────────────────────────────
INSTALLED_APPS = [
    'daphne',                           # FIRST — enables ASGI/WebSocket support
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels',
    'cloudinary',                       # Fix 2: Cloud file storage
    'cloudinary_storage',               # Fix 2: Replaces local /media/ folder
    # Local
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',    # Fix 5: Serve static files in production
    'corsheaders.middleware.CorsMiddleware',         # Fix 6: Must be before CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# ─────────────────────────────────────────────
# Database — Fix 8: Use Neon pooled connection
# ─────────────────────────────────────────────
# Local: postgres://postgres:1234@localhost:5432/multi_tenant_db
# Neon:  postgresql://user:pass@ep-xxx-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require
DATABASES = {
    'default': env.db(),
}
# Enable connection pooling to prevent Neon free-tier timeouts
DATABASES['default']['CONN_MAX_AGE'] = 60
DATABASES['default']['OPTIONS'] = DATABASES['default'].get('OPTIONS', {})
DATABASES['default']['OPTIONS']['connect_timeout'] = 10


# ─────────────────────────────────────────────
# Password Validation
# ─────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ─────────────────────────────────────────────
# Internationalization
# ─────────────────────────────────────────────
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ─────────────────────────────────────────────
# Static Files — Fix 5: Whitenoise for production
# ─────────────────────────────────────────────
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# ─────────────────────────────────────────────
# File Storage — Fix 2: Cloudinary (free 25GB)
# ─────────────────────────────────────────────
# Local development: files saved to /media/
# Production: files saved to Cloudinary (free tier — no AWS needed)
CLOUDINARY_URL = env('CLOUDINARY_URL', default='')
if CLOUDINARY_URL:
    # Production: use Cloudinary for all file uploads
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.RawMediaCloudinaryStorage'
    MEDIA_URL = '/media/'
else:
    # Local development: use local filesystem
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'


# ─────────────────────────────────────────────
# Default Primary Key
# ─────────────────────────────────────────────
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'core.User'


# ─────────────────────────────────────────────
# CORS — Fix 6: Whitelist Vercel domain
# ─────────────────────────────────────────────
# In DEBUG mode, allow all origins (for local development)
# In production, only allow the specific Vercel domain
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = env.list(
        'CORS_ALLOWED_ORIGINS',
        default=['http://localhost:5173']
    )
    CORS_ALLOW_CREDENTIALS = True


# ─────────────────────────────────────────────
# Django REST Framework
# ─────────────────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# ─────────────────────────────────────────────
# Email
# ─────────────────────────────────────────────
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@saasplatform.com'


# ─────────────────────────────────────────────
# Document Encryption Key (Fernet AES-128)
# ─────────────────────────────────────────────
DOCUMENT_ENCRYPTION_KEY = env('DOCUMENT_ENCRYPTION_KEY')


# ─────────────────────────────────────────────
# Django Channels (WebSockets)
# ─────────────────────────────────────────────
# CRITICAL: Must use RedisChannelLayer in production.
# InMemoryChannelLayer ONLY works in a single process — broken on Render.
# RedisChannelLayer uses Upstash so web + worker can share WebSocket state.
ASGI_APPLICATION = 'backend.asgi.application'

_redis_url = env('REDIS_URL')

if _redis_url.startswith('rediss://'):
    # Upstash TLS Redis — must pass ssl_cert_reqs
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [{
                    'address': _redis_url,
                    'ssl_cert_reqs': None,
                }],
            },
        }
    }
else:
    # Local Redis (no TLS)
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [_redis_url],
            },
        }
    }


# ─────────────────────────────────────────────
# Celery — Fix 1: Separate Web + Worker on Render
# ─────────────────────────────────────────────
# Web service start command:    daphne -b 0.0.0.0 -p $PORT backend.asgi:application
# Worker start command:         celery -A backend worker --loglevel=info --pool=solo
import ssl

CELERY_BROKER_URL = env('REDIS_URL')
CELERY_RESULT_BACKEND = env('REDIS_URL')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
# Fix 4: Reduce Redis usage — tasks expire after 1 hour
CELERY_RESULT_EXPIRES = 3600
# Upstash uses rediss:// (TLS) — ssl.CERT_NONE skips cert verification (required for Upstash free tier)
CELERY_BROKER_USE_SSL = {
    'ssl_cert_reqs': ssl.CERT_NONE
}
CELERY_REDIS_BACKEND_USE_SSL = {
    'ssl_cert_reqs': ssl.CERT_NONE
}
